version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: sleep for waiting launch db
          command: sleep 1
      - run:
          name: "before_test: setup db"
          command: docker-compose run web rails db:create db:migrate
      - run:
          name: test
          command: docker-compose run web rails test
      - run:
          name: docker-compose down
          command: docker-compose down
  deploy:
    docker:
      - image: centos:7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINT
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -p 22 "cd ~/rails-app/; git pull origin master; sudo ./entrypoint.sh down; sudo ./entrypoint.sh build; sudo ./entrypoint.sh up -d"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master